import {
  Briefcase,
  Building2,
  ChartColumn,
  Check,
  ChevronDown,
  CircleCheck,
  CircleHelp,
  CirclePause,
  Clock,
  Contrast,
  Copy,
  Ellipsis,
  ExternalLink,
  FileText,
  Flag,
  Globe,
  GraduationCap,
  HandHeart,
  HardHat,
  Heart,
  Keyboard,
  LayoutGrid,
  Leaf,
  MapPin,
  Navigation,
  Phone,
  Receipt,
  Scale,
  Search,
  Shield,
  Sprout,
  Stethoscope,
  Target,
  Umbrella,
  Users,
  Volume2,
  Wallet,
  X,
  ZoomIn,
} from 'lucide-static';

/** Lucide icons (ISC license), inlined at build time. Content refers to them by these names. */
export const icons = {
  certificates: FileText,
  business: Briefcase,
  tax: Receipt,
  social: HandHeart,
  health: Stethoscope,
  agriculture: Sprout,
  infrastructure: HardHat,
  education: GraduationCap,
  safety: Shield,
  environment: Leaf,
  office: Building2,
  phone: Phone,
  search: Search,
  external: ExternalLink,
  map: MapPin,
  scale: Scale,
  wallet: Wallet,
  umbrella: Umbrella,
  chart: ChartColumn,
  clock: Clock,
  help: CircleHelp,
  chevronDown: ChevronDown,
  copy: Copy,
  check: Check,
  checkCircle: CircleCheck,
  close: X,
  more: Ellipsis,
  target: Target,
  flag: Flag,
  grid: LayoutGrid,
  heart: Heart,
  users: Users,
  navigation: Navigation,
  keyboard: Keyboard,
  sound: Volume2,
  zoom: ZoomIn,
  contrast: Contrast,
  pause: CirclePause,
  globe: Globe,
} as const;

export type IconName = keyof typeof icons;
export const iconNames = Object.keys(icons) as [IconName, ...IconName[]];
